name: Analyse

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

jobs:
  job:
    name: Analyse
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init
        uses: github/codeql-action/init@v1

      - name: Analyse
        uses: github/codeql-action/analyze@v1
